# Generated by Django 4.1.7 on 2023-05-16 16:40

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "onprem_sid",
                    django_cryptography.fields.encrypt(
                        models.CharField(max_length=200)
                    ),
                ),
                (
                    "name",
                    django_cryptography.fields.encrypt(
                        models.CharField(max_length=200)
                    ),
                ),
                ("email", models.CharField(max_length=200)),
                (
                    "question_one",
                    django_cryptography.fields.encrypt(
                        models.CharField(
                            choices=[
                                ("0", "What was your childhood nickname?"),
                                (
                                    "1",
                                    "In what city did you meet your spouse/significant other?",
                                ),
                                (
                                    "2",
                                    "What is the name of your favorite childhood friend?",
                                ),
                                ("3", "What street did you live on in third grade?"),
                                (
                                    "4",
                                    "What is your oldest sibling’s birthday month and year? (e.g., January 1900)",
                                ),
                                (
                                    "5",
                                    "What is the middle name of your youngest child?",
                                ),
                                ("6", "What is your oldest sibling's middle name?"),
                                ("7", "What school did you attend for sixth grade?"),
                                (
                                    "8",
                                    "What was your childhood phone number including area code? (e.g., 000-000-0000)",
                                ),
                                (
                                    "9",
                                    "What is your oldest cousin's first and last name?",
                                ),
                                (
                                    "10",
                                    "What was the name of your first stuffed animal?",
                                ),
                                (
                                    "11",
                                    "In what city or town did your mother and father meet?",
                                ),
                                ("12", "Where were you when you had your first kiss?"),
                                (
                                    "13",
                                    "What is the first name of the boy or girl that you first kissed?",
                                ),
                                (
                                    "14",
                                    "What was the last name of your third grade teacher?",
                                ),
                                ("15", "In what city does your nearest sibling live?"),
                                (
                                    "16",
                                    "What is your youngest brother’s birthday month and year? (e.g., January 1900)",
                                ),
                                (
                                    "17",
                                    "What is your maternal grandmother's maiden name?",
                                ),
                                ("18", "In what city or town was your first job?"),
                                (
                                    "29",
                                    "What is the name of the place your wedding reception was held?",
                                ),
                                (
                                    "20",
                                    "What is the name of a college you applied to but didn't attend?",
                                ),
                                (
                                    "21",
                                    "Where were you when you first heard about 9/11?",
                                ),
                            ],
                            max_length=200,
                        )
                    ),
                ),
                (
                    "answer_one",
                    django_cryptography.fields.encrypt(
                        models.CharField(max_length=200)
                    ),
                ),
                (
                    "question_two",
                    django_cryptography.fields.encrypt(
                        models.CharField(
                            choices=[
                                ("0", "What was your childhood nickname?"),
                                (
                                    "1",
                                    "In what city did you meet your spouse/significant other?",
                                ),
                                (
                                    "2",
                                    "What is the name of your favorite childhood friend?",
                                ),
                                ("3", "What street did you live on in third grade?"),
                                (
                                    "4",
                                    "What is your oldest sibling’s birthday month and year? (e.g., January 1900)",
                                ),
                                (
                                    "5",
                                    "What is the middle name of your youngest child?",
                                ),
                                ("6", "What is your oldest sibling's middle name?"),
                                ("7", "What school did you attend for sixth grade?"),
                                (
                                    "8",
                                    "What was your childhood phone number including area code? (e.g., 000-000-0000)",
                                ),
                                (
                                    "9",
                                    "What is your oldest cousin's first and last name?",
                                ),
                                (
                                    "10",
                                    "What was the name of your first stuffed animal?",
                                ),
                                (
                                    "11",
                                    "In what city or town did your mother and father meet?",
                                ),
                                ("12", "Where were you when you had your first kiss?"),
                                (
                                    "13",
                                    "What is the first name of the boy or girl that you first kissed?",
                                ),
                                (
                                    "14",
                                    "What was the last name of your third grade teacher?",
                                ),
                                ("15", "In what city does your nearest sibling live?"),
                                (
                                    "16",
                                    "What is your youngest brother’s birthday month and year? (e.g., January 1900)",
                                ),
                                (
                                    "17",
                                    "What is your maternal grandmother's maiden name?",
                                ),
                                ("18", "In what city or town was your first job?"),
                                (
                                    "29",
                                    "What is the name of the place your wedding reception was held?",
                                ),
                                (
                                    "20",
                                    "What is the name of a college you applied to but didn't attend?",
                                ),
                                (
                                    "21",
                                    "Where were you when you first heard about 9/11?",
                                ),
                            ],
                            max_length=200,
                        )
                    ),
                ),
                (
                    "answer_two",
                    django_cryptography.fields.encrypt(
                        models.CharField(max_length=200)
                    ),
                ),
                (
                    "question_three",
                    django_cryptography.fields.encrypt(
                        models.CharField(
                            choices=[
                                ("0", "What was your childhood nickname?"),
                                (
                                    "1",
                                    "In what city did you meet your spouse/significant other?",
                                ),
                                (
                                    "2",
                                    "What is the name of your favorite childhood friend?",
                                ),
                                ("3", "What street did you live on in third grade?"),
                                (
                                    "4",
                                    "What is your oldest sibling’s birthday month and year? (e.g., January 1900)",
                                ),
                                (
                                    "5",
                                    "What is the middle name of your youngest child?",
                                ),
                                ("6", "What is your oldest sibling's middle name?"),
                                ("7", "What school did you attend for sixth grade?"),
                                (
                                    "8",
                                    "What was your childhood phone number including area code? (e.g., 000-000-0000)",
                                ),
                                (
                                    "9",
                                    "What is your oldest cousin's first and last name?",
                                ),
                                (
                                    "10",
                                    "What was the name of your first stuffed animal?",
                                ),
                                (
                                    "11",
                                    "In what city or town did your mother and father meet?",
                                ),
                                ("12", "Where were you when you had your first kiss?"),
                                (
                                    "13",
                                    "What is the first name of the boy or girl that you first kissed?",
                                ),
                                (
                                    "14",
                                    "What was the last name of your third grade teacher?",
                                ),
                                ("15", "In what city does your nearest sibling live?"),
                                (
                                    "16",
                                    "What is your youngest brother’s birthday month and year? (e.g., January 1900)",
                                ),
                                (
                                    "17",
                                    "What is your maternal grandmother's maiden name?",
                                ),
                                ("18", "In what city or town was your first job?"),
                                (
                                    "29",
                                    "What is the name of the place your wedding reception was held?",
                                ),
                                (
                                    "20",
                                    "What is the name of a college you applied to but didn't attend?",
                                ),
                                (
                                    "21",
                                    "Where were you when you first heard about 9/11?",
                                ),
                            ],
                            max_length=200,
                        )
                    ),
                ),
                (
                    "answer_three",
                    django_cryptography.fields.encrypt(
                        models.CharField(max_length=200)
                    ),
                ),
            ],
        ),
    ]
